package com.arabsoft.mySTKE.security.habilitation.model;

// Generated 25 janv. 2013 15:44:07 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;
import org.springframework.security.core.GrantedAuthority;

/**
 * Profil generated by hbm2java
 */
@Entity
@Table(name = "PROFIL")
public class Profil implements GrantedAuthority, java.io.Serializable {

	private String codPflPfl;
	private String libPflPfl;
	private String libHdebPfl;
	private String libHfinPfl;
	private String codNivhPfl;
	private Boolean boolEtatPfl;
	private Boolean boolJouvPfl;
	private String codCatpPfl;
	private Set<UserRole> userRoles = new HashSet<UserRole>(0);


	public Profil() {
	}

	public Profil(String codPflPfl, String libPflPfl, String libHdebPfl,
			String libHfinPfl, String codNivhPfl) {
		this.codPflPfl = codPflPfl;
		this.libPflPfl = libPflPfl;
		this.libHdebPfl = libHdebPfl;
		this.libHfinPfl = libHfinPfl;
		this.codNivhPfl = codNivhPfl;
	}

	public Profil(String codPflPfl,  String libPflPfl,
			String libHdebPfl, String libHfinPfl, String codNivhPfl,
			Boolean boolEtatPfl, Boolean boolJouvPfl, String codCatpPfl,
			Set<UserRole> userRoles) {
		this.codPflPfl = codPflPfl;
		this.libPflPfl = libPflPfl;
		this.libHdebPfl = libHdebPfl;
		this.libHfinPfl = libHfinPfl;
		this.codNivhPfl = codNivhPfl;
		this.boolEtatPfl = boolEtatPfl;
		this.boolJouvPfl = boolJouvPfl;
		this.codCatpPfl = codCatpPfl;
		this.userRoles = userRoles;
		
	}

	@Id
	@Column(name = "COD_PFL_PFL",  length = 10)
	public String getCodPflPfl() {
		return this.codPflPfl;
	}

	public void setCodPflPfl(String codPflPfl) {
		this.codPflPfl = codPflPfl;
	}

	

	@Column(name = "LIB_PFL_PFL", nullable = false, length = 60)
	public String getLibPflPfl() {
		return this.libPflPfl;
	}

	public void setLibPflPfl(String libPflPfl) {
		this.libPflPfl = libPflPfl;
	}

	@Column(name = "LIB_HDEB_PFL", nullable = false, length = 5)
	public String getLibHdebPfl() {
		return this.libHdebPfl;
	}

	public void setLibHdebPfl(String libHdebPfl) {
		this.libHdebPfl = libHdebPfl;
	}

	@Column(name = "LIB_HFIN_PFL", nullable = false, length = 5)
	public String getLibHfinPfl() {
		return this.libHfinPfl;
	}

	public void setLibHfinPfl(String libHfinPfl) {
		this.libHfinPfl = libHfinPfl;
	}

	@Column(name = "COD_NIVH_PFL", nullable = false, length = 10)
	public String getCodNivhPfl() {
		return this.codNivhPfl;
	}

	public void setCodNivhPfl(String codNivhPfl) {
		this.codNivhPfl = codNivhPfl;
	}

	@Column(name = "BOOL_ETAT_PFL", precision = 1, scale = 0)
	public Boolean getBoolEtatPfl() {
		return this.boolEtatPfl;
	}

	public void setBoolEtatPfl(Boolean boolEtatPfl) {
		this.boolEtatPfl = boolEtatPfl;
	}

	@Column(name = "BOOL_JOUV_PFL", precision = 1, scale = 0)
	public Boolean getBoolJouvPfl() {
		return this.boolJouvPfl;
	}

	public void setBoolJouvPfl(Boolean boolJouvPfl) {
		this.boolJouvPfl = boolJouvPfl;
	}

	@Column(name = "COD_CATP_PFL", length = 3)
	public String getCodCatpPfl() {
		return this.codCatpPfl;
	}

	public void setCodCatpPfl(String codCatpPfl) {
		this.codCatpPfl = codCatpPfl;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "profil")
	public Set<UserRole> getUserRoles() {
		return this.userRoles;
	}

	public void setUserRoles(Set<UserRole> userRoles) {
		this.userRoles = userRoles;
	}

	@Transient
	@Override
	public String getAuthority() {
		return getCodPflPfl();
	}

	public String toString() {
		return new ToStringBuilder(this, ToStringStyle.SIMPLE_STYLE).append(
				this.codPflPfl).toString();
	}

}
