package com.arabsoft.mySTKE.security.habilitation.model;

// Generated 25 janv. 2013 15:44:07 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UtilisateurProfilId generated by hbm2java
 */
@Embeddable
public class UserRoleId implements java.io.Serializable {

	private String codPflPfl;
	private String numMatrUser;

	public UserRoleId() {
	}

	public UserRoleId(String codPflPfl, String numMatrUser) {
		this.codPflPfl = codPflPfl;
		this.numMatrUser = numMatrUser;
	}

	@Column(name = "COD_PFL_PFL", nullable = false, length = 10)
	public String getCodPflPfl() {
		return this.codPflPfl;
	}

	public void setCodPflPfl(String codPflPfl) {
		this.codPflPfl = codPflPfl;
	}

	@Column(name = "NUM_MATR_USER", nullable = false, length = 10)
	public String getNumMatrUser() {
		return this.numMatrUser;
	}

	public void setNumMatrUser(String numMatrUser) {
		this.numMatrUser = numMatrUser;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserRoleId))
			return false;
		UserRoleId castOther = (UserRoleId) other;

		return ((this.getCodPflPfl() == castOther.getCodPflPfl()) || (this
				.getCodPflPfl() != null && castOther.getCodPflPfl() != null && this
				.getCodPflPfl().equals(castOther.getCodPflPfl())))
				&& ((this.getNumMatrUser() == castOther.getNumMatrUser()) || (this
						.getNumMatrUser() != null
						&& castOther.getNumMatrUser() != null && this
						.getNumMatrUser().equals(castOther.getNumMatrUser())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCodPflPfl() == null ? 0 : this.getCodPflPfl().hashCode());
		result = 37
				* result
				+ (getNumMatrUser() == null ? 0 : this.getNumMatrUser()
						.hashCode());
		return result;
	}

}
